# URL of the Google Sheet listing papers
# The sheet must be shared with your service account or publicly. See 'Setup'
# section of README.md for details.
sheet_url: null

# Email to include in API queries. Configuring this allows you to use Crossref's
# less-congested 'polite' API pool. If unset, bibtools will try to use your git
# email (from `git config user.email`). For more info see
# https://github.com/CrossRef/rest-api-doc#good-manners--more-reliable-service
contact_email: null
